### PR TITLE
 basic_operations

### PR DESCRIPTION
**Pull request by pallasite99**
Switch case required

### CODE REVIEW

**Comment by kartikpingale** [comment]
# creating a single input function that will accept any matrix

**Comment by pallasite99** [comment]
Okay.

**Comment by kartikpingale** [comment]
_lets work on determinants_

**Comment by pallasite99** [comment]
Yeah. Lets start on it.

**Comment by kartikpingale** [comment]
if m=n --> proceed
else --> not defined

m, n are rows and columns

**Comment by kartikpingale** [comment]
if m=2
det = a11*a22 - a12-a21

**Comment by kartikpingale** [comment]
if m=3
minor11 = //some code here
minor 12 = //same
minor 13 = //it's getting irritating
det = a11*minor11 + .............

**Comment by pallasite99** [comment]
This is very the complexity increases. Need to make it easy to understand for 3×3

**Comment by kartikpingale** [comment]
let's try for 2x2 first...

**Pull request closed without merging**
